# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install
  displayName: 'npm install'
- script: npm install newman
  displayName: 'install newman'
- script: 'newman run rb.postman_collection.json -e remote.postman_environment.json --reporters cli,junit --reporter-junit-export junitReport.xml'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'

