# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'imo(e32a0df0-b1a8-4d22-b40d-249314b27946)'
    KeyVaultName: 'az-mykeyvault'
    SecretsFilter: 'mySecretName'
    RunAsPreJob: false

- script: echo $(mySecretName)  > secret.txt
- publish: secret.txt
